name: SonarCloud Full Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis (Frontend only)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend dependencies
        run: |
          cd Frontend
          npm install

      - name: Run Frontend tests with coverage
        run: |
          cd Frontend 
          npx vitest run --coverage

      - name: Prepare LCOV for SonarCloud
        run: |
          mkdir -p coverage
          cp Frontend/coverage/lcov.info coverage/merged-lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
